# Generated by Django 5.0.6 on 2024-06-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=60)),
                ('year', models.IntegerField(null=True)),
                ('decription', models.TextField()),
            ],
        ),
    ]
