# Generated by Django 5.0.6 on 2024-06-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_movieinfoms_titel_movieinfoms_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('year', models.IntegerField(null=True)),
                ('decription', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='MovieInfoms',
        ),
    ]
