# Generated by Django 5.0.6 on 2024-07-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_movieinfo_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieinfo',
            old_name='img',
            new_name='imgs',
        ),
    ]
